services:
  # Redis - Message queue and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # API Gateway - Request routing and rate limiting
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - WORKFLOW_SERVICE_URL=http://workflow-service:8001
      - VIDEO_PROCESSOR_URL=http://video-processor:8002
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
    volumes:
      - ./services/api-gateway/src:/app/src
      - ./shared:/app/shared
    depends_on:
      - redis
    networks:
      - youtube-transcriber

  # Video Processor - YouTube video download and processing
  video-processor:
    build:
      context: ./services/video-processor
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
      - PORT=8002
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - DOWNLOAD_DIR=/app/downloads
      - OUTPUT_DIR=/app/output
    volumes:
      - ./services/video-processor/src:/app/src
      - video-downloads:/app/downloads
      - video-output:/app/output
    depends_on:
      - redis
    networks:
      - youtube-transcriber

  # Transcription Service - Audio transcription coordination
  transcription-service:
    build:
      context: ./services/transcription-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
      - PORT=8003
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - LLM_SERVICE_URL=http://llm-service:8005
    volumes:
      - ./services/transcription-service/src:/app/src
    depends_on:
      - redis
    networks:
      - youtube-transcriber

volumes:
  redis-data:
    driver: local
  video-downloads:
    driver: local
  video-output:
    driver: local

networks:
  youtube-transcriber:
    driver: bridge
