services:
  # Frontend - React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api-gateway
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # API Gateway - Express Gateway for request routing and rate limiting
  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
    depends_on:
      - workflow-service
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


  # Workflow Service - Integrated ReAct workflow engine with media processing
  workflow-service:
    build:
      context: ./services/workflow-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=development
      - PORT=8004
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_DEFAULT_MODEL=llama2:7b
      - LOG_LEVEL=debug
      - DOWNLOAD_DIR=/app/downloads
      - OUTPUT_DIR=/app/output
      - WHISPER_MODELS_DIR=/app/models
      # Optional: Add OpenAI API key for Whisper API instead of local
      # - OPENAI_API_KEY=your_openai_api_key_here
    volumes:
      - ./services/workflow-service/src:/app/src
      - workflow-downloads:/app/downloads
      - workflow-output:/app/output
      - whisper-models:/app/models
    depends_on:
      - ollama
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama - Local LLM server
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=llama2:7b
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


volumes:
  ollama-data:
    driver: local
  whisper-models:
    driver: local
  workflow-downloads:
    driver: local
  workflow-output:
    driver: local

networks:
  youtube-transcriber:
    driver: bridge
