services:
  # Frontend - React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api-gateway
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis - Message queue and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # API Gateway - Request routing and rate limiting
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - WORKFLOW_SERVICE_URL=http://workflow-service:8004
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
    volumes:
      - ./services/api-gateway/src:/app/src
      - ./shared:/app/shared
    depends_on:
      - redis
      - workflow-service
    networks:
      - youtube-transcriber


  # Workflow Service - Integrated ReAct workflow engine with media processing
  workflow-service:
    build:
      context: ./services/workflow-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=development
      - PORT=8004
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_DEFAULT_MODEL=llama2:7b
      - LOG_LEVEL=debug
      - DOWNLOAD_DIR=/app/downloads
      - OUTPUT_DIR=/app/output
      - WHISPER_MODELS_DIR=/app/models
      # Optional: Add OpenAI API key for Whisper API instead of local
      # - OPENAI_API_KEY=your_openai_api_key_here
    volumes:
      - ./services/workflow-service/src:/app/src
      - workflow-downloads:/app/downloads
      - workflow-output:/app/output
      - whisper-models:/app/models
    depends_on:
      - redis
      - ollama
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama - Local LLM server
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=llama2:7b
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


volumes:
  redis-data:
    driver: local
  ollama-data:
    driver: local
  whisper-models:
    driver: local
  workflow-downloads:
    driver: local
  workflow-output:
    driver: local

networks:
  youtube-transcriber:
    driver: bridge
