services:
  # Redis - Message queue and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - youtube-transcriber
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # API Gateway - Request routing and rate limiting
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - WORKFLOW_SERVICE_URL=http://workflow-service:8001
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
    volumes:
      - ./services/api-gateway/src:/app/src
      - ./shared:/app/shared
    depends_on:
      - redis
    networks:
      - youtube-transcriber

volumes:
  redis-data:
    driver: local

networks:
  youtube-transcriber:
    driver: bridge
