# Express Gateway System Configuration

# Database configuration (using in-memory for simplicity)
db:
  redis:
    host: localhost
    port: 6379
    namespace: EG

# Session configuration
session:
  secret: youtube-transcriber-gateway-secret
  resave: false
  saveUninitialized: false

# Logging configuration
logging:
  level: info
  format: combined

# CORS default settings
cors:
  origin: true
  credentials: true

# Rate limiting default settings
rateLimiting:
  store: memory
  windowMs: 900000  # 15 minutes
  max: 100
  message: 'Too many requests, please try again later'

# Request size limits
requestSizeLimit:
  limit: '10mb'

# Health check settings
healthCheck:
  interval: 30000  # 30 seconds
  timeout: 5000    # 5 seconds

# Security headers
security:
  contentSecurityPolicy:
    directives:
      defaultSrc: ["'self'"]
      styleSrc: ["'self'", "'unsafe-inline'"]
      scriptSrc: ["'self'"]
      imgSrc: ["'self'", "data:", "https:"]
